name: "publish"
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: install dependencies (ubuntu only)
      if: matrix.platform == 'ubuntu-20.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev webkit2gtk-4.0 libappindicator3-dev librsvg2-dev patchelf
    - name: Rust setup
      uses: dtolnay/rust-toolchain@stable
    - name: Rust cache
      uses: swatinem/rust-cache@v2
      with:
        workspaces: './src-tauri -> target'
    - name: Sync node version and setup cache
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: 'yarn' # Set this to npm, yarn or pnpm.
    - name: Install frontend dependencies
      # If you don't have `beforeBuildCommand` configured you may want to build your frontend here too.
      run: yarn # Change this to npm, yarn or pnpm.
    - name: Build the app
      uses: tauri-apps/tauri-action@v0

      env:
        GITHUB_TOKEN: ${{ secrets.TAURI_TOKEN }}
      with:
        tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
        releaseName: "App v__VERSION__"
        releaseBody: "See the assets to download this version and install."
        releaseDraft: true
        prerelease: false
